"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiV1 = void 0;
const express_1 = require("express");
const orders_controller_1 = require("../controllers/orders_controller");
const delivery_agent_controller_1 = require("../controllers/delivery_agent_controller");
const restaurants_controller_1 = require("../controllers/restaurants_controller");
const restaurants_middleware_1 = require("../middlewares/restaurants.middleware");
const delivery_agent_middleware_1 = require("../middlewares/delivery_agent.middleware");
const order_middleware_1 = require("../middlewares/order.middleware");
exports.apiV1 = (0, express_1.Router)();
exports.apiV1.post("/orders", order_middleware_1.validateOrder, orders_controller_1.createRestaurantOrder);
exports.apiV1.get("/orders/:user_id", orders_controller_1.getUserOrders);
exports.apiV1.put("/orders/:order_id", order_middleware_1.validateOrderRating, orders_controller_1.updateOrderRating);
exports.apiV1.put("/orders/:order_id", order_middleware_1.validateOrderStatus, orders_controller_1.updateOrderStatus);
exports.apiV1.get("/delivery_agents", delivery_agent_controller_1.getAvailableDeliveryAgents);
exports.apiV1.put("/delivery_agents/:delivery_agent_id", delivery_agent_middleware_1.validateDeliveryAgent, delivery_agent_controller_1.updateDeliveryAgentStatus);
exports.apiV1.get("/restaurants", restaurants_controller_1.getOnlineRestaurants);
exports.apiV1.put("/restaurants/:restaurant_id", restaurants_middleware_1.validateRestaurant, restaurants_controller_1.updateRestaurantAvailabilty);
exports.apiV1.put("/restaurants", restaurants_middleware_1.validateRestaurantMenu, restaurants_controller_1.updateRestaurantMenu);
